blank_issues_enabled: true
contact_links:
  - name: Steam Workshop Page
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=2438225189
    about: Questions, gameplay help, and general discussion about EasyPacking.